### ISSUE TITLE
Make default tab configurable

### ISSUE THREAD

**Issue by nichtich** [pkiraly/qa-catalogue-web#106]
There should be a configuration key to set the default tab, shown at the base tab if no tab has been selected.

See also #104 for use case.

**Comment by pkiraly** [comment]
done.

documentation:

`default-tab`: the tab which will be displayed when no tab is selected. This will be the tab which will be opened by 
   the root URL (the landing page). If no default-tab has been set, `completeness` will be used. The possible values are: `data`,
   `completeness` (default), `issues`, `functions`, `classifications`, `authorities`, `serials`, `tt-completeness`,
   `shelf-ready-completeness`, `shacl`, `network`, `terms`, `pareto`, `history`, `timeline`, `settings`, `about`,
   `record-issues`, `histogram`, `functional-analysis-histogram`, `control-fields`, `download`, `collocations`.

**Comment by nichtich** [comment]
Thanks!
