### ISSUE TITLE
Link to field documentation in completeness tab

### ISSUE THREAD

**Issue by nichtich** [pkiraly/qa-catalogue-web#119]
Each field in the completeness tab table should be linked with *(i)* to field documentation:

![image](https://github.com/pkiraly/qa-catalogue-web/assets/299856/37b5ca67-37cf-4727-bd7d-478f557ef50c)

**Comment by pkiraly** [comment]
estimation: 2 hours

**Comment by pkiraly** [comment]
@nichtich it is testable in the devel branch.
![image](https://github.com/pkiraly/qa-catalogue-web/assets/218218/7b85204a-542f-4a44-abb9-8b119e3be74e)

**Comment by nichtich** [comment]
Looks good but then the `i` icon should also be removed in the issues tab. I did so in #75929ca.
