### ISSUE TITLE
post-install-cmd section is not executed after install

### ISSUE THREAD

**Issue by pkiraly** [pkiraly/qa-catalogue-web#129]
The [composer documentation](https://getcomposer.org/doc/articles/scripts.md#command-events) says:

>  `post-install-cmd`: occurs after the install command has been executed with a lock file present

since we do not add `composer.lock` into git, these scripts are not executed.

Solutions:

* EITHER run `composer install` twice - first time it will install dependencies and create `composer.lock`, the second time due to the existence of this file the scripts will be executed.
* OR find another event which is not dependent on the existence of `.lock` file
* OR add `composer.lock` to git.

Running the same command twice is not elegant. I am not sure about the current best practice but an older tutorial ([Learning Composer, the PHP Dependency Manager](https://www.linkedin.com/learning/learning-composer-the-php-dependency-manager/)) suggests to add `.lock` to git, in order to be sure that all user uses the exact same versions of the dependent libraries (the `.json` file might have version ranges, such as `~1.0` or `^1.0` or `1.0.*`, while `.lock` doesn't).

@nichtich Do you have any experience in it?

**Comment by nichtich** [comment]
Adding `composer.lock` is best practice.

**Comment by pkiraly** [comment]
Thanks!
