### ISSUE TITLE
Add logger

### ISSUE THREAD

**Issue by nichtich** [pkiraly/qa-catalogue-web#146]
`error_log` is used in some places for tracing and debugging. Configuration should include settings for log level and internally use a PSR-3 compatible logging library such as Monolog, e.g.

~~~php
$config->log->error("...")
$config->log->info("...")
$config->log->debug("...")
~~~

For debugging, the log level would be changed in configuration. Logging target could be `stderr` (error_log, the default as now), `file`, and `syslog`, this should be enough to support.

**Comment by pkiraly** [comment]
Agree, it is a technical debt of the project.

**Comment by pkiraly** [comment]
Here is a basic usage of Monolog:

```php
use Monolog\Level;
use Monolog\Logger;
use Monolog\Handler\StreamHandler;

// create a log channel
$log = new Logger('name');
$log->pushHandler(new StreamHandler('path/to/your.log', Level::Warning));

// add records to the log
$log->warning('Foo');
$log->error('Bar');
```
The `'path/to/your.log'` part could be read from configuration, but what would you like to see as default value, something like `log/qa-catalogue.log`?

**Comment by pkiraly** [comment]
We will use 2.5 because it supports PHP 7.2. monolog 3.x supports PHP 8.x only.
```bash
composer require monolog/monolog:^2.5
```

**Comment by nichtich** [comment]
I've extened the logger to use `error_log` by default and configurable to log to a file. Other methods such as `syslog` may be added if needed.

**Comment by pkiraly** [comment]
@nichtich  Thanks! However I do not see your commits. Did you pushed them?

**Comment by nichtich** [comment]
See [#de3bd88718cc0b](https://github.com/pkiraly/qa-catalogue-web/commit/de3bd88718cc0bac71c76d174a91e152412f3694)

**Comment by pkiraly** [comment]
Sorry, I checked the main. Now I have reviewed it and merged to the main via a PR.
