### ISSUE TITLE
More detailed information about source of data

### ISSUE THREAD

**Issue by nichtich** [pkiraly/qa-catalogue-web#159]
User feedback shows that the information about source of data is not sufficient. Several values (date of source data, date of analysis generation, catalogue URL...) should be combined in the "about" tab to tell where the data comes from, how it was processed, when it will be updated next... 

This may be solved by simple configuration of about template, so not sure yet whether change in the software is needed.

**Comment by pkiraly** [comment]
- the times and the parameters of the individual analyses are stored in the `[analysis].params.json` files, and there are functions to read them. It needs some more development
- date of data: we also read it from a file created during the analysis
- catalogue URL: it is recorded in the catalogue classes or from configuration
- "how it was processed": I am not sure I understand what exactly is required. Maybe it needs additional configuration.
