### ISSUE TITLE
Configuration: remove multitenant key

### ISSUE THREAD

**Issue by nichtich** [pkiraly/qa-catalogue-web#162]
The configuration key `multitenant` should be removed, it is only used internally in Configuration class. A configuration file such as

~~~
versions=false
versions[loc]=true
~~~

could be used both multitenant and single instance. If `id` is `loc` then `doVersioning()` would return `true` else `false`. No need to explicitly enable/disable multitenant!

**Comment by pkiraly** [comment]
For the time being I would like to keep it. The thing is that during our cooperation several times I had the feeling that some features should behave differently if the web UI serves a single catalogue or multiple ones. My suggestion: keep it say for 2 months. If by end of January we will not use it elsewhere, let's drop it.
