### ISSUE TITLE
Replace error_log with logger to support log levels

### ISSUE THREAD

**Issue by nichtich** [pkiraly/qa-catalogue-web#193]
Setting `logLevel` configuration does not affect `error_log`. All 70 calls to `error_log` should be replaced by calls to the logger (see `$this->log->...`).

**Comment by pkiraly** [comment]
You are right.

**Comment by pkiraly** [comment]
@nichtich I changed in the main, "tab" classes. There are some static functions used by the dashboard, where I kept `error_log` in the first round - probably the index.php should create a global logger, that can be used by these and the auxiliary functions. I also improved the README a bit.

**Comment by nichtich** [comment]
In general globals should be avoided, but having a global logger object seems legit.

**Comment by pkiraly** [comment]
Now `error_log()` calls are purged out of the tool.
