### ISSUE TITLE
How to display multiple catalogues in the web application

### ISSUE THREAD

**Issue by Phu2** [pkiraly/qa-catalogue-web#214]
We have two catalogues and would them displayed in the web application. Is that feasible?

The [README](https://github.com/pkiraly/qa-catalogue-web?tab=readme-ov-file#configuration) states:

> Multiple catalogues can be configured in one file.

So i tried in `config/configuration.cnf`:

```
id=hbz
catalogue[hbz]=hbz
indexName[hbz]=hbz
dirName[hbz]=hbz

id=hbz-update
catalogue[hbz-update]=hbz_update
indexName[hbz-update]=hbz-update
dirName[hbz-update]=hbz-update
```

The web app shows only the latter one under the `[BASE URL]/qa-catalogue/` path. 

I also tried some Apache configurations as suggested in the README:

```
<Directory /var/www/html/hbz>
  AllowOverride All
  Order allow,deny
  allow from all
</Directory>
```
but no luck, requesting `[BASE URL]/hbz/` results in 404.

It is not clear to me how this is intended to work. The web application is installed under `/var/www/html/qa-catalogue`. We are using the [Docker setup of the main qa-catalogue project](https://github.com/pkiraly/qa-catalogue/blob/main/Dockerfile#L64).

**Comment by Phu2** [comment]
Related: https://github.com/pkiraly/qa-catalogue-web/issues/114

**Comment by pkiraly** [comment]
You should do it in two steps:

1) create symbolic links in web server directory:

```
$ ls -la /var/www/html/
... hbz -> /path/to/qa-catalogue-web
... hbz_update -> /path/to/qa-catalogue-web
```

2) adjust the config file

Please add the following line:
```
multitenant=true
```
remove the lines
```
id=hbz
id=hbz-update
```

**Comment by Phu2** [comment]
Thanks, it works great! I had already created the symlinks out of suspicion. (In my case it has to be `hbz-update` not `hbz_update`) The `multitenant` config option is not documented anywhere, isn't it?

**Comment by pkiraly** [comment]
Unfortunately it is not documented indeed (as I aware nobody wanted to host multiple dashboards). I made a ticket for that so it will be documented, and there will be a section for this topic. Thanks for spotting this issue!

**Comment by Phu2** [comment]
> as I aware nobody wanted to host multiple dashboards

We are happy to be the first ones ;)

**Comment by Phu2** [comment]
Closing
