### ISSUE TITLE
Change name of repository

### ISSUE THREAD

**Issue by nichtich** [pkiraly/qa-catalogue-web#77]
This is not urgent because the public name is already "QA Catalogue" or "QA Catalogue Web" but the repository could also be moved from `metadata-qa-marc-web` to `qa-catalogue-web`. I sometimes also use the name "Metadata Quality Analysis (MQA)" but  "QA Catalogue" seems the more official name. There is also the name "Metadata Quality Assessment Framework (MQAF)" for the set of components (QA Catalogue Backend and Frontend but also other tools), so some clarification of names could make sense anyway.

**Comment by pkiraly** [comment]
Metadata Quality Assessment Framework (MQAF) (metadata-qa-api) is the name of the basic Java library, on top of which QA catalogue (the backend, metadata-qa-marc) sits on top of which QA Catalogue Web (metadata-qa-marc-web) sites.
Change the name is easy, but the change of URL require investiging the following questions:
- [ ] Is it possible to change the URL of the repository?
- [ ] If it is possible: is there a redirection from the old URL to the new URL?

**Comment by nichtich** [comment]
GitHub redirects renamed repositores, even cloning and pushing from/to old URL still works.
